### PR TITLE
Updated logo and added multiple requests feature

### PR DESCRIPTION
**Pull request by sudhz**
Added multiple requests feature

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

I'm still working on adding timestamp and url in each response.

### CODE REVIEW

**Comment by rufilboy** [comment]
How will the user input more than one URL?

**Comment by sudhz** [comment]
1. Enter one URL
2. Click on "Analyze"
3. The results are shown
4. Re-enter different URL
5. Click on "Analyze" again

**Comment by rufilboy** [comment]
image

Ohhh, awesome
But can you also work on adding support to indicate the result of each request separately?

**Comment by rufilboy** [comment]
Addresses #40

**Comment by sudhz** [comment]
Do you mean to say that I should add the URL and timestamp in each response? Because the response is shown individually for each request.

**Comment by rufilboy** [comment]
Yeah, you get it

But I was thinking, adding the whole URL won't be that good as it might look nice, what do you think we can do?

**Comment by sudhz** [comment]
How about setting an ID for each request?

**Comment by rufilboy** [comment]
Yeah

**Comment by sudhz** [comment]
Alright, I'll work on it

**Comment by sudhz** [comment]
Hi, instead of generating a unique ID for each request on the client side, wouldn't it be a better option to do it on the server side and send the response back with the ID? This is the response from the backend URL, which is https://logiqapi.onrender.com/api/analyze:
image
As you can notice here, there is no ID property. Instead of setting a new unique ID on each request on the client size, wouldn't it be better if we handled it on the server side and sent a response like:
```JSON
{
   "ID":"ccf7b488-9171-449f-aaca-5e36f94ef455",
   "URL":"https://google.com/",
   "isUp":true,
   "ipAddress":"142.251.33.78",
   "uptime":"99.00",
   "responseTime":"0.16"
}
```
Now, this would be for a successful response, when the URL is valid.

If the URL is invalid, your backend just sends the following response:
image
Instead of handling the invalid URL requests like this, you can send the response from the backend like:
```JSON
{
   "ID":"ccf7b488-9171-449f-aaca-5e36f94ef455",
   "URL":"<the invalid url>",
   "isUp":false,
   "ipAddress":null,
   "uptime":null,
   "responseTime":null
}
```
What are your thoughts on this?

**Comment by rufilboy** [comment]
Yeah yeah, I want to said it ealier

**Comment by rufilboy** [comment]
Do you have time to work on it on the backend side?

**Comment by sudhz** [comment]
Yeah, sure, let me know the details

**Pull request merged**
